# 你可以从官方示例里直接复制
# https://github.com/lowlighter/metrics/blob/master/metrics-config.yml

# 用户名
username: Karcen
title: "GitHub Metrics"
display:
  stats: true
  languages: true
  commits_calendar: true
  streaks: true
  trophies: true
theme:
  background: "radical"
