name: æ›´æ–°GitHubä¸ªäººèµ„æ–™README

on:
  schedule:
    # æ¯24å°æ—¶è¿è¡Œä¸€æ¬¡
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: æ›´æ–°README
        run: |
          # åŠ¨æ€åˆ›å»ºREADMEå†…å®¹
          cat > README.md << EOL
          # ðŸ‘‹ ä½ å¥½ï¼Œæˆ‘æ˜¯ Karcen

          ## ðŸš€ å…³äºŽæˆ‘
          çƒ­è¡·äºŽå°–ç«¯æŠ€æœ¯å’Œåˆ›æ–°è§£å†³æ–¹æ¡ˆçš„å¼€å‘è€…ï¼Œä¸“æ³¨äºŽæœºå™¨å­¦ä¹ å’Œæ•°æ®ç§‘å­¦é¢†åŸŸã€‚

          ## ðŸ“Š GitHubç»Ÿè®¡
          ![GitHubç»Ÿè®¡](https://github-readme-stats.vercel.app/api?username=Karcen&show_icons=true&theme=radical&include_all_commits=true&count_private=true)

          ## ðŸ”¥ æœ€å¸¸ç”¨ç¼–ç¨‹è¯­è¨€
          ![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=Karcen&layout=compact&langs_count=7&theme=radical)

          ## ðŸ† è´¡çŒ®streak
          ![Streakç»Ÿè®¡](https://github-readme-streak-stats.herokuapp.com/?user=Karcen&theme=radical)

          ## ðŸ› ï¸ æŠ€æœ¯æ ˆ
          ![Python](https://img.shields.io/badge/-Python-05122A?style=flat&logo=python)
          ![PyTorch](https://img.shields.io/badge/-PyTorch-05122A?style=flat&logo=pytorch)
          ![æœºå™¨å­¦ä¹ ](https://img.shields.io/badge/-æœºå™¨å­¦ä¹ -05122A?style=flat&logo=tensorflow)

          ## ðŸŒ± å½“å‰å…´è¶£
          - æœºå™¨å­¦ä¹ 
          - æ•°æ®ç§‘å­¦
          - äººå·¥æ™ºèƒ½

          ## ðŸ’¬ è”ç³»æˆ‘
          [![é‚®ç®±](https://img.shields.io/badge/-é‚®ç®±-c14438?style=flat-square&logo=Gmail&logoColor=white)](mailto:karcenzheng@yeah.net)
          

          ---

          â­ï¸ æ¥è‡ª [Karcen](https://github.com/Karcen)
          EOL

      - name: æäº¤å˜æ›´
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "æ›´æ–°æœ€æ–°GitHubç»Ÿè®¡ä¿¡æ¯" || exit 0
          git push
