name: Update GitHub Profile README

on:
  schedule:
    # Runs every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README
        run: |
          # Create README content dynamically
          cat > README.md << EOL
          # 👋 Hello, I'm Karcen (Jiacheng Zheng)

          ## 🚀 About Me
          I'm a passionate developer with a keen interest in cutting-edge technologies and innovative solutions.

          ## 📊 GitHub Stats
          ![GitHub Stats](https://github-readme-stats.vercel.app/api?username=Karcen&show_icons=true&theme=radical&include_all_commits=true&count_private=true)

          ## 🔥 Most Used Languages
          ![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=Karcen&layout=compact&langs_count=7&theme=radical)

          ## 🏆 Contribution Streak
          ![Streak Stats](https://github-readme-streak-stats.herokuapp.com/?user=Karcen&theme=radical)

          ## 🛠️ Tech Stack
          ![Python](https://img.shields.io/badge/-Python-05122A?style=flat&logo=python)
          ![PyTorch](https://img.shields.io/badge/-PyTorch-05122A?style=flat&logo=pytorch)
          ![Machine Learning](https://img.shields.io/badge/-Machine%20Learning-05122A?style=flat&logo=tensorflow)

          ## 🌱 Current Interests
          - Machine Learning
          - Data Science
          - Artificial Intelligence

          ## 💬 Connect with Me
          [![Email](https://img.shields.io/badge/-Email-c14438?style=flat-square&logo=Gmail&logoColor=white)](mailto:your-email@example.com)
          [![LinkedIn](https://img.shields.io/badge/-LinkedIn-blue?style=flat-square&logo=Linkedin&logoColor=white)](https://www.linkedin.com/in/your-profile/)

          ---

          ⭐️ From [Karcen](https://github.com/Karcen)
          EOL

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest stats" || exit 0
          git push